/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-west-1",
  aws_cognito_identity_pool_id:
    "eu-west-1:879198d5-3e77-40d7-9090-45e2174123e2",
  aws_cognito_region: "eu-west-1",
  aws_user_pools_id: "eu-west-1_6EmHIyP8F",
  aws_user_pools_web_client_id: "3387h78g5knhth3g0a6ds2h57g",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://b2n735ypw5aebhhprkuczd2fjm.appsync-api.eu-west-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-west-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-fdwiyj3bwvba5eehnh6azzcbsa",
  aws_user_files_s3_bucket: "viaweba3e7179aa111445aace0066c7bc6d2ce194052-dev",
  aws_user_files_s3_bucket_region: "eu-west-1",
  predictions: {
    identify: {
      identifyEntities: {
        proxy: false,
        region: "eu-west-1",
        celebrityDetectionEnabled: true,
      },
      identifyLabels: {
        proxy: false,
        region: "eu-west-1",
        defaults: {
          type: "LABELS",
        },
      },
    },
    convert: {
      speechGenerator: {
        region: "eu-west-1",
        proxy: false,
        defaults: {
          VoiceId: "Matthew",
          LanguageCode: "en-US",
        },
      },
    },
  },
}

export default awsmobile
